### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by YazidKurdi** [laudanum123/fantasy_fabricator#10]
Hey laudanum

I have been watching this repo grow and checking all the updates you are making to the website, I would like to contribute if that is okay.
If not I will continue to lurk in the repo 😄

**Comment by laudanum123** [comment]
Hey YazidKurdi,
I would be delighted if you are willing to contribute to the project. I have a couple of open points right now which are most "urgent" :-)
I am not that knowledgeable how to best coordinate work on github. If you have any ideas where we can collect and coordinate work on new features please tell me.
Right now the following things are most needed:
- Improve the quality of the Named Entity Recognition which is implemented using the Spacy library. Right now it does not seem to work very well as it misses a lot of the NPC names and locations. Maybe we could also tell GPT3 in our initial prompt that it should somehow highlight all NPC names and location names. Some experimentation would be needed I guess
- Character Creator for Character Stats and backstory
-  Location Creator for Location Details

**Comment by YazidKurdi** [comment]
Thanks @laudanum123 !
I suggest writing up each feature in a separate issue, if there are a lot of features, separating them into - high, medium, and low - labels would be best. To avoid duplicating work you can assign tasks you are working on to yourself and I can propose to be assigned certain tasks which you can approve.

As for now, I can work on the Named Entity Recognition feature, I noticed there were duplicated entities and mislabeled objects as entities.
What are you looking to achieve with this feature? An end user would select his saved campaign from db and show a list/table/card of entities to him?
What is an entity?


Idea template (if necessary):
## Idea Description

Please provide a clear and concise description of the idea. 

## Problem Solved

What problem does this idea solve or what need does it meet?

## Proposed Solution

Describe the solution you are proposing. 

## Advantages

What are the benefits of this idea? How does it compare to current solutions or workarounds?

## Use Cases

Please describe some examples of how this idea could be used in practice. 

## Additional Context

Add any other relevant information about the idea here. This could include similar ideas or related issues, potential drawbacks, or questions that need to be answered before implementation.

**Comment by laudanum123** [comment]
That sounds very good. Let's do this!

**Comment by YazidKurdi** [comment]
Great!
Want to hop on discord for better ideas communication?

**Comment by laudanum123** [comment]
sure!

**Comment by laudanum123** [comment]
you already got a server?

**Comment by laudanum123** [comment]
my user is laudanum#5804
