### ISSUE TITLE
Named Entity Recognition for NPC and Location

### ISSUE THREAD

**Issue by laudanum123** [laudanum123/fantasy_fabricator#11]
## Idea Description
The app should automatically pick up NPC and location names from newly created adventures and enable the user to quickly create background info and stats for them by clicking on their name and being referred to the NPC or location creator page.

## Solved Problem
Dungeon Masters (DMs) often spend a lot of time creating and maintaining NPC and location details for their adventures. This process can be time-consuming and repetitive, taking away from the creative and improvisational aspects of being a DM. This app solves this problem by providing an efficient and streamlined way for DMs to generate and manage NPC and location information.

## Proposed Solution:
The proposed solution is a dungeon master helper application that uses the spaCy Named Entity Recognition (NER) library and GPT-3 to generate NPC and location details. The app automatically picks up NPC and location names from newly created adventures using the spaCy NER library and provides an interface for the user to quickly create background information and stats for these characters and locations by clicking on their names. GPT-3 will then generate detailed information for the selected NPC or location.

## Advantages:
The app provides a more efficient and convenient way for DMs to create and manage NPC and location details compared to manual methods. With the use of GPT-3, the app can generate detailed and unique information for each NPC and location, reducing the time and effort required for DMs to create these details from scratch.

## Use Cases:

- A DM who is running a new adventure and needs to quickly generate background information for several NPCs and locations.
- A DM who is preparing for a session and needs to review and make updates to the NPC and location details.
- A DM who wants to create a library of NPCs and locations for use in future adventures.

## Additional Context:
This idea is similar to existing NPC generators and worldbuilding tools, but it leverages the advanced natural language generation capabilities of GPT-3 to provide more detailed and unique information. Potential drawbacks may include the need for a reliable internet connection and the potential for GPT-3 generated information to be inappropriate or inappropriate for certain audiences. Further consideration should also be given to the user interface and ease of use for the app.

**Comment by YazidKurdi** [comment]
@laudanum123 

I am thinking of the following flow: (bolded points are questions)

1. User creates an adventure - API call to GPT (Already done)
2. Given the adventure ID, adventure components (Title, hook, plot etc..) are merged into one corpus and refed to GPT to extract NPCs and locations:

- Given adventure ID, create the backend to extract the entities
**- Extracted entities to be displayed in a table/card - What do you think?**

**3. NPCs and locations are then stored in the entities table (Do you think NPCs and locations should each have their own table, or both of them in one "Entities" table?**
4. Allow the user to add notes/lore onto each extracted entity, if cards are chosen as a method of display, they can be flipped to provide a textbox for the user to add extra information

Notes:

**- Do we need to integrate with other views? (i.e redirect from adventure build to entities page)**
- Will go with GPT approach rather than spaCy for now, seems more streamlined and robust to errors


Let me know what you think

**Comment by laudanum123** [comment]
Hi @YazidKurdi ,

Thanks for your message. I would say the following to your points:
- Point 2: Yes, I agree that we should display the extracted entities in an additional card but also just highlight them as a link in the adventure text, so the user can click on it and has the option to either view existing background info/stats on the entity or create it using GPT. I guess for that purpose we need a link to the NPC/Location creators which is prepopulated with the Entity name.
- I think for it to work we need to also provide the complete adventure to GPT again + the request to create the background for the character. Otherwise GPT won't know how the NPC/Location is connected to the adventure and just create random stuff
- Point 3: 
I think NPC and Location should be in separate tables probably because it gives us more flexibility later on

I think using GPT instead of Spacy is the way to go for NER.

Regards

**Comment by YazidKurdi** [comment]
Hi @laudanum123 

> * Point 2: Yes, I agree that we should display the extracted entities in an additional card but also just highlight them as a link in the adventure text, so the user can click on it and has the option to either view existing background info/stats on the entity or create it using GPT. I guess for that purpose we need a link to the NPC/Location creators which is prepopulated with the Entity name.

Created a new branch [Here](https://github.com/laudanum123/fantasy_fabricator/tree/NPC/Location_feature)
Great to hear your thoughts

For your point on "highlight them as a link in the adventure text", I have created an "NPCs" array on the frontend along with the already existing "adventure" object in the "AdventureView" view. How can we go about creating NPC URL links with each occurrence of them in the "AdventureView" view, or do you have another approach in mind?

**Comment by laudanum123** [comment]
Hi @YazidKurdi,

There already exists a method in the adventureView.vue file which takes care of highlighting entities in the text. I think you just have to replace the names with your new variables:
```python
highlightEntities() {
            // iterate through adventure components and highlight named entities
            const adventureComponents = [
                this.adventure.AdventureHook,
                this.adventure.AdventureNPCs,
                this.adventure.AdventurePlot,
                this.adventure.AdventureClimax,
                this.adventure.AdventureResolution
            ];
            const adventure = reactive(this.adventure);
            let keys = Object.keys(adventure);
            adventureComponents.forEach((component, index) => {
                let highlightedText = component;
                this.named_entities.forEach((entity) => {
                    const link = `<a href="/npc?id=${entity.id}">${entity.entity_name}</a>`;
                    highlightedText = highlightedText.replace(entity.entity_name, link);
                });
                adventure[keys[index]] = highlightedText;
            });
            this.adventure = adventure;
        }

    }
```

**Comment by YazidKurdi** [comment]
#16 Solved

**Comment by laudanum123** [comment]
@YazidKurdi Could you check what happened to the app.py file? app.py is now importing app from main but there does not seem to be an app.py file under main. Could you check and maybe commit the app.py  file you are using under main?
Thanks!

**Comment by YazidKurdi** [comment]
@laudanum123 Fixed
