### ISSUE TITLE
Add Game System to Adventure

### ISSUE THREAD

**Issue by laudanum123** [laudanum123/fantasy_fabricator#14]
@YazidKurdi : At some step the game system should be assigned to an adventure. Otherwise the NPC stats and maybe even location stats created for the adventure might end up differing because the AI created them for the wrong system.
Maybe we should add this step after the adventure has been created on the adventureBuilder View. So after the adventure has been created by the AI the user can specify a game system for the adventure. Or should the system be assigned before the creation of the adventure? We could just store it and not pass it to the AI as it is not required for creating a story and should also not bias the system into a certain direction. What do you think?

**Comment by YazidKurdi** [comment]
@laudanum123, this is already being implemented in [character_generator](https://github.com/laudanum123/fantasy_fabricator/tree/character_generator) branch correct?
Where game system is introduced in NPC generation rather than adventure building phase

**Comment by laudanum123** [comment]
Yes, exactly. Hopefully I will manage to work on it tomorrow evening. Von meinem iPhone gesendetAm 16.02.2023 um 22:44 schrieb YazidKurdi ***@***.***>:﻿
@laudanum123, this is already being implemented in character_generator branch correct?
Where game system is introduced in NPC generation rather than adventure building phase
