### ISSUE TITLE
Fix order of AdventureHook and AdventureNPC in AdventureView

### ISSUE THREAD

**Issue by laudanum123** [laudanum123/fantasy_fabricator#18]
In the AdventureView the output of NPC and Hook seem to be swapped. I did not immediately find the bug.

**Comment by YazidKurdi** [comment]
Is this specific to a certain adventure, looks good to me as below, and matches what is in the db.

![image](https://user-images.githubusercontent.com/50083367/218552352-18d1c223-1348-4f8b-86be-ec8e950f3563.png)
