### ISSUE TITLE
generateAdventure(), type error

### ISSUE THREAD

**Issue by YazidKurdi** [laudanum123/fantasy_fabricator#2]
This is returning a type error.

https://github.com/laudanum123/fantasy_fabricator/blob/903975b7b856540234877b5317dc55db4cb4c724/frontend/src/components/adventure_builder.vue#L158

To return the title, hook,plot, etc.. cards, code modified to:

```
this.adventure = response.data.message
```

What would be the outcome if that LOC was not present

**Comment by laudanum123** [comment]
should be fixed with latest merge
